import {z} from 'zod'
import {sceneSchema} from './scene'
import {getAgentScene,applyAgentScene} from './agentSceneStore'
import type {WebMcpToolDefinition} from '../webmcp/registry'
const common={domain:'visual' as const,requiresApproval:false,connectionStatus:'CONNECTED' as const,verificationPolicy:'Validated scene data only; no arbitrary code execution or manufacturing claim',outputSchema:{type:'object',additionalProperties:true}}
export const agentSceneTools:WebMcpToolDefinition[]=[
 {...common,name:'get_3d_modeling_request',readOnly:true,description:'Read the latest user modeling request and revision. The browser does not run an LLM; you, the connected agent, design the requested mesh. Units centimetres, Y up, CCW triangles. Read get_3d_scene_schema and deliver with apply_3d_model_scene. Do not substitute an unrelated preset.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({...getAgentScene(),scene:undefined,sceneName:getAgentScene().scene?.name??null})},
 {...common,name:'get_3d_scene_schema',readOnly:true,description:'JSON schema for arbitrary multi-part meshes accepted by the studio and Blender add-on. Flat vertices in centimetres, triangle indices, UV pairs and materials. No list of permitted object names.',inputSchema:{type:'object',properties:{},additionalProperties:false},execute:async()=>({schema:z.toJSONSchema(sceneSchema),coordinates:'centimetres, Y up; CCW triangles',limits:'200000 total vertices; 256 parts; no executable code'})},
 {...common,name:'apply_3d_model_scene',readOnly:false,description:'Replace the home studio model with a newly designed scene. Supply expectedRevision and requestId read before modeling. Rejects stale results. Updates actual preview and downloadable Blender scene; does not launch desktop Blender.',inputSchema:{type:'object',properties:{scene:z.toJSONSchema(sceneSchema),expectedRevision:{type:'integer'},requestId:{type:['string','null']}},required:['scene','expectedRevision','requestId'],additionalProperties:false},execute:async(input:unknown)=>{const p=z.object({scene:sceneSchema,expectedRevision:z.number().int().positive(),requestId:z.string().nullable()}).strict().safeParse(input);return p.success?applyAgentScene(p.data.scene,p.data.expectedRevision,p.data.requestId):{state:'FAIL',errors:p.error.issues.map(x=>x.message)}}},
]
