import * as T from './vendor/three/build/three.module.min.js';
import {GLTFLoader} from './vendor/three/examples/jsm/loaders/GLTFLoader.js';
import {GLTFExporter} from './vendor/three/examples/jsm/exporters/GLTFExporter.js';
import {STLExporter} from './vendor/three/examples/jsm/exporters/STLExporter.js';
import {World} from './world.mjs';
import {build,dimensions,inspect} from './geometry.mjs';
import {parsePrompt,compilePrompt,finite,progress,validateGLB,validateTransform,SOURCE_MODELS,LABELS,escapeCSV} from './core.mjs';
import {saveAsset,listAssets,getAsset,saveWorld,loadWorld,sha256,durableStorage} from './archive.mjs';
import {makeAudio} from './audio.mjs';
import * as oracle from './oracle.mjs';
const $=s=>document.querySelector(s),$$=s=>[...document.querySelectorAll(s)];
let world,assets=[],busy=false,stop=false,start=0,timer,activeJob=null,photoURL,soundOn=false,toastTimer,basket=new Map(),saveChain=Promise.resolve();
const elapsed=ms=>`${Math.floor(ms/60000)}:${String(Math.floor(ms/1000)%60).padStart(2,'0')}`;
const toast=message=>{$('#toast').textContent=message;$('#toast').hidden=false;clearTimeout(toastTimer);toastTimer=setTimeout(()=>$('#toast').hidden=true,7000);};
function log(text,user=false){const p=document.createElement('p');p.textContent=text;p.classList.toggle('user',user);$('#chat-log').appendChild(p);$('#chat-log').scrollTop=99999;}
function download(blob,name){const u=URL.createObjectURL(blob),a=document.createElement('a');a.href=u;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(u),30000);}
function setTab(id){$$('.panel').forEach(e=>e.classList.toggle('active',e.id===id));$$('[data-tab]').forEach(e=>e.classList.toggle('active',e.dataset.tab===id));}
function updatePrompt(){try{const text=compilePrompt($('#prompt').value,{instructions:$('#extra').value,size:$('#size').value,texture:$('#texture').value,purpose:$('#purpose').value});$('#compiled').value=text;$('#char-count').textContent=`${text.length} / 9999`;$('#generate').disabled=busy;}catch(e){$('#compiled').value='';$('#char-count').textContent=e.message;$('#generate').disabled=true;}}
function begin(title){if(busy)throw Error('Poczekaj na bieżące zlecenie.');busy=true;stop=false;start=performance.now();$('#progress-title').textContent=title;$('#progress-dialog').showModal();$('#close-progress').hidden=true;$('#stop-queue').hidden=false;$('#orb').classList.remove('done');$('#progress-note').textContent='Procent odnosi się do rzeczywiście wykonanych etapów.';updateProgress(0,'Przygotowanie');timer=setInterval(()=>$('#elapsed').textContent=elapsed(performance.now()-start),250);updatePrompt();}
function updateProgress(n,stage,eta=null){$('#stage').textContent=stage;$('#percent').textContent=n===null?'…':n+'%';$('#water').style.height=(n??0)+'%';if(n===null)$('#progress-bar').removeAttribute('value');else $('#progress-bar').value=n;$('#eta').textContent=eta===null?'Brak pomiaru':elapsed(Math.max(0,eta*1000));$('#elapsed').textContent=elapsed(performance.now()-start);}
function finish(error){clearInterval(timer);busy=false;activeJob=null;$('#close-progress').hidden=false;$('#stop-queue').hidden=true;$('#orb').classList.add('done');if(error){$('#stage').textContent=error.message;$('#eta').textContent='Zatrzymano';log(error.message);}else updateProgress(100,'Gotowe. Wynik zapisany w archiwum.',0);updatePrompt();}
async function toGLB(object){return new Blob([await new GLTFExporter().parseAsync(object,{binary:true,onlyVisible:false})],{type:'model/gltf-binary'});}
async function fromGLB(blob){const buffer=await blob.arrayBuffer();validateGLB(buffer);return new Promise((resolve,reject)=>new GLTFLoader().parse(buffer,'',g=>resolve(g.scene),reject));}
async function archiveObject(object,info){const blob=await toGLB(object);const record={id:crypto.randomUUID(),createdAt:new Date().toISOString(),type:'model',blob,sha256:await sha256(blob),review:'unreviewed',...info,report:inspect(object)};await saveAsset(record);await refreshAssets();return record;}
function persistWorld(){if(!world)return;const data=world.serialize();saveChain=saveChain.then(()=>saveWorld(data)).catch(()=>toast('Nie udało się zapisać świata. Pobierz archiwum ZIP.'));}
function addToWorld(object,record,position){const i=world.entities.size,report=record.report??inspect(object);const max=Math.max(...Object.values(report.dimensions))/1000;const worldSize=record.spec?.kind==='house'?5:record.spec?.kind==='iss'?10:2;const transform={x:position?.x??((i%6)-2.5)*3.5,y:position?.y??0,z:position?.z??(5+Math.floor(i/6)*3.5),rotation:0,scale:worldSize/Math.max(max,.001)};object.name=record.name;const id=world.add(object,{id:crypto.randomUUID(),assetId:record.id,transform,zone:world.mode});world.select(id);persistWorld();}
function selectEntity(e){const r=assets.find(a=>a.id===e.assetId);$('#selected-name').textContent=e.object.name;const d=r?.report?.dimensions;$('#selected-info').textContent=d?`${d.x.toFixed(1)} × ${d.y.toFixed(1)} × ${d.z.toFixed(1)} mm · ${Math.round(r.report.triangles).toLocaleString('pl')} trójkątów · oryginał`:'Obiekt w świecie';$('#pos-x').value=e.object.position.x.toFixed(2);$('#pos-z').value=e.object.position.z.toFixed(2);$('#rotation').value=T.MathUtils.radToDeg(e.object.rotation.y).toFixed(1);$('#scale').value=e.object.scale.x.toFixed(3);}
async function generate(){if(busy)return;let copies;try{copies=$('#order-mode').value==='many'?finite($('#quantity').value,1,50,'Liczba kopii'):1;if(!Number.isInteger(copies))throw Error('Liczba kopii musi być całkowita.');updatePrompt();if(!$('#compiled').value)throw Error('Popraw opis i limit polecenia.');if($('#engine').value==='oracle'&&!oracle.isConnected())throw Error('Połącz Oracle, aby uruchomić Astrę i Blendera.');if($('#engine').value==='local'&&$('#photo').files.length)throw Error('Zdjęcie wymaga trybu Astra + Blender.');begin(copies>1?`Tworzenie ${copies} kopii`:'Tworzenie modelu 3D');
  if($('#engine').value==='oracle'){await generateOracle(copies);return;}
  const p=parsePrompt($('#prompt').value,{size:$('#size').value});updateProgress(12,'Rozpoznano geometrię: '+LABELS[p.kind]);await new Promise(requestAnimationFrame);
  const object=build(p);updateProgress(40,'Geometria zbudowana. Eksportuję GLB.');await new Promise(requestAnimationFrame);
  const record=await archiveObject(object,{name:LABELS[p.kind],spec:p,prompt:$('#compiled').value,copies,origin:'parametric',textureMode:'PBR material factors; no image texture maps'});updateProgress(80,'GLB zapisany. Dodaję kopie do świata.');
  for(let i=0;i<copies;i++){if(stop)break;addToWorld(i?await fromGLB(record.blob):object,record);updateProgress(80+Math.round((i+1)/copies*19),`Dodano ${i+1} / ${copies}`);await new Promise(requestAnimationFrame);}finish();log(`Zapisano ${record.name}. Oryginał: maks. ${p.size} mm. Kopie w świecie współdzielą jeden plik, więc nie generujemy ponownie tej samej geometrii.`);
}catch(e){if(busy)finish(e);else toast(e.message);}}
async function generateOracle(copies){try{const id=crypto.randomUUID();activeJob=id;const photos=await oracle.photoPayload($('#photo').files[0],Number($('#texture').value));await oracle.request('/api/jobs',{method:'POST',body:JSON.stringify({id,prompt:$('#prompt').value,agentInstructions:$('#compiled').value,photos,copies})});localStorage.setItem('forge-pending-job',id);updateProgress(null,'Oracle przyjął zlecenie.');await watchJob(id,copies);}catch(e){finish(e);}}
async function watchJob(id,copies=1){for(;;){const j=await oracle.request('/api/jobs/'+id);if(['failed','cancelled','needs-input'].includes(j.state))throw Error(j.detail??'Zlecenie zatrzymane.');updateProgress(progress(j.progress,j.state),j.detail??j.state,j.etaSeconds??null);if(j.state==='succeeded'){const blob=await oracle.request('/api/jobs/'+id+'/model');const object=await fromGLB(blob);const record={id:crypto.randomUUID(),name:j.name??'Model Astra + Blender',createdAt:new Date().toISOString(),type:'model',blob,sha256:await sha256(blob),origin:'oracle',jobId:id,prompt:$('#compiled').value,report:inspect(object),review:'unreviewed'};await saveAsset(record);await refreshAssets();for(let i=0;i<copies;i++)addToWorld(i?await fromGLB(blob):object,record);localStorage.removeItem('forge-pending-job');finish();return;}await new Promise(r=>setTimeout(r,2500));}}
async function refreshAssets(){assets=(await listAssets()).sort((a,b)=>b.createdAt.localeCompare(a.createdAt));$('#count').textContent=assets.length;$('#assets').replaceChildren();for(const a of assets){const card=document.createElement('article');card.className='asset-card';const name=document.createElement('b');name.textContent=a.name;card.appendChild(name);const meta=document.createElement('p');meta.textContent=`${a.type==='model'?'GLB':a.type==='texture'?'PNG':'WAV'} · ${(a.blob.size/1048576).toFixed(2)} MB · ${new Date(a.createdAt).toLocaleString('pl')}`;card.appendChild(meta);const status=document.createElement('small');status.textContent=a.review==='accepted'?'Sprawdzony przez autora':'Wersja robocza · oceń przed drukiem';card.appendChild(status);const row=document.createElement('div');row.className='row';for(const [label,fn]of [['Pobierz',()=>download(a.blob,`${a.name}-${a.id.slice(0,8)}.${a.type==='model'?'glb':a.type==='texture'?'png':'wav'}`)],...(a.type==='model'?[['Do świata',async()=>{try{addToWorld(await fromGLB(a.blob),a);toast('Model dodany do świata.');}catch(e){toast(e.message);}}],['Do B2B',()=>{basket.set(a.id,(basket.get(a.id)??0)+1);renderBasket();toast('Dodano do zestawienia B2B.');}]]:[])]){const b=document.createElement('button');b.textContent=label;b.onclick=fn;row.appendChild(b);}card.appendChild(row);$('#assets').appendChild(card);}renderOriginals();}
function renderOriginals(){$('#originals').replaceChildren();for(const source of SOURCE_MODELS){const a=assets.find(x=>x.jobId===source.id),card=document.createElement('div');card.className='source-card';const title=document.createElement('b');title.textContent=source.name;const p=document.createElement('p');p.textContent=a?'Kopia GLB zapisana na tym urządzeniu · SHA-256 sprawdzone.':source.status;card.append(title,p);$('#originals').appendChild(card);}}
function renderBasket(){$('#basket').replaceChildren();for(const [id,qty]of basket){const a=assets.find(x=>x.id===id);if(!a)continue;const row=document.createElement('div'),label=document.createElement('label'),input=document.createElement('input');label.textContent=a.name;input.type='number';input.min=0;input.max=10000;input.value=qty;input.onchange=()=>{try{const n=finite(input.value,0,10000,'Ilość');if(!Number.isInteger(n))throw Error('Podaj pełną liczbę sztuk.');n?basket.set(id,n):basket.delete(id);renderBasket();}catch(e){toast(e.message);}};label.appendChild(input);row.appendChild(label);$('#basket').appendChild(row);}if(!basket.size)$('#basket').textContent='Dodaj modele przyciskiem „Do B2B” w archiwum.';}
async function syncOriginals(){try{if(!oracle.isConnected())throw Error('Połącz Oracle, aby skopiować najnowszą Julię i Królową.');begin('Archiwizowanie Julii i Królowej');for(let i=0;i<SOURCE_MODELS.length;i++){const source=SOURCE_MODELS[i];const blob=await oracle.request('/api/archive/'+source.id);const hash=await sha256(blob);if(!assets.some(a=>a.jobId===source.id&&a.sha256===hash)){const object=await fromGLB(blob);await saveAsset({id:crypto.randomUUID(),name:source.name,createdAt:new Date().toISOString(),type:'model',blob,sha256:hash,jobId:source.id,origin:'oracle',review:'unreviewed',report:inspect(object)});}updateProgress((i+1)*50,source.name+' skopiowana.');}await refreshAssets();finish();}catch(e){if(busy)finish(e);else toast(e.message);}}
async function backup(){try{begin('Zapisywanie archiwum ZIP');await saveChain;const list=await listAssets(),zip=new JSZip();const manifest={version:1,createdAt:new Date().toISOString(),world:world.serialize(),assets:[]};let i=0;for(const a of list){const {blob,...meta}=a;const ext=a.type==='model'?'glb':a.type==='texture'?'png':'wav';const path=`assets/${a.id}.${ext}`;zip.file(path,blob);manifest.assets.push({...meta,path});updateProgress(Math.round(++i/Math.max(list.length,1)*70),'Pakowanie '+a.name);}zip.file('manifest.json',JSON.stringify(manifest,null,2));const blob=await zip.generateAsync({type:'blob',compression:'STORE'},p=>updateProgress(70+Math.round(p.percent*.29),'Tworzenie pliku ZIP'));download(blob,'FORGE-world-archive.zip');finish();}catch(e){finish(e);}}
async function restore(file){try{if(!file||file.size>250*1024*1024)throw Error('Archiwum ZIP: maks. 250 MB.');begin('Odtwarzanie archiwum');const zip=await JSZip.loadAsync(file);const entries=Object.values(zip.files);if(entries.length>500||entries.reduce((s,e)=>s+(e._data?.uncompressedSize??0),0)>300*1024*1024)throw Error('Archiwum przekracza limit rozpakowania.');const mf=zip.file('manifest.json');if(!mf||(mf._data?.uncompressedSize??0)>2*1024*1024)throw Error('Brak manifestu lub za duży manifest.');const m=JSON.parse(await mf.async('string'));if(m.version!==1||!Array.isArray(m.assets)||m.assets.length>200)throw Error('Nieobsługiwany manifest.');const prepared=[];for(const a of m.assets){if(!/^[a-f0-9-]{36}$/.test(a.id)||!/^assets\/[a-f0-9-]{36}\.(glb|png|wav)$/.test(a.path)||!['model','texture','audio'].includes(a.type))throw Error('Niepoprawny wpis archiwum.');const entry=zip.file(a.path);if(!entry)throw Error('Brak pliku: '+a.path);const blob=await entry.async('blob');if(await sha256(blob)!==a.sha256)throw Error('Niezgodna suma SHA-256: '+a.name);if(a.type==='model')validateGLB(await blob.arrayBuffer());prepared.push({...a,blob});}for(const a of prepared)if(!assets.some(x=>x.id===a.id))await saveAsset(a);await refreshAssets();if(m.world?.entities){for(const e of m.world.entities){if(world.entities.has(e.id))continue;const a=assets.find(x=>x.id===e.assetId&&x.type==='model');if(!a)continue;world.add(await fromGLB(a.blob),{...e,zone:e.zone==='iss'?'iss':'earth',transform:validateTransform(e.transform)});}persistWorld();}finish();}catch(e){if(busy)finish(e);else toast(e.message);}}
async function importFiles(files){try{begin('Zapisywanie modeli GLB');for(let i=0;i<files.length;i++){const f=files[i],object=await fromGLB(f),hash=await sha256(f);const existing=assets.find(a=>a.sha256===hash);if(existing){addToWorld(object,existing);continue;}const record={id:crypto.randomUUID(),name:f.name.replace(/\.glb$/i,''),createdAt:new Date().toISOString(),type:'model',blob:f,sha256:hash,origin:'import',review:'unreviewed',report:inspect(object)};await saveAsset(record);await refreshAssets();addToWorld(object,record);updateProgress(Math.round((i+1)/files.length*99),'Zapisano '+f.name);}finish();}catch(e){if(busy)finish(e);else toast(e.message);}}
async function exportSelected(format){try{const a=assets.find(a=>a.id===world.selected?.assetId);if(!a)throw Error('Wybierz obiekt w świecie.');if(format==='glb'){download(a.blob,a.name+'.glb');return;}const o=await fromGLB(a.blob),d=dimensions(o);o.scale.multiplyScalar(100/Math.max(d.x,d.y,d.z)*1000);o.updateMatrixWorld(true);const data=new STLExporter().parse(o,{binary:true});download(new Blob([data],{type:'application/octet-stream'}),a.name+'-100mm-roboczy.stl');toast('STL ma maks. 100 mm. Sprawdź siatkę, połączenia i grubości w slicerze.');}catch(e){toast(e.message);}}
async function generateTexture(){try{const size=Number($('#texture-export-size').value),kind=$('#texture-type').value;begin(`Tekstura ${size} × ${size}`);const worker=new Worker('./texture-worker.mjs',{type:'module'});const result=await new Promise((resolve,reject)=>{worker.onmessage=({data})=>{if(data.error){reject(Error(data.error));worker.terminate();}else if(data.blob){resolve(data);worker.terminate();}else updateProgress(data.progress,'Tworzenie pikseli materiału.');};worker.onerror=e=>{reject(Error(e.message||'Brak wsparcia generacji tekstur na tym urządzeniu.'));worker.terminate();};worker.postMessage({size,kind});});const record={id:crypto.randomUUID(),name:`${kind}-${size}`,createdAt:new Date().toISOString(),type:'texture',blob:result.blob,sha256:await sha256(result.blob),resolution:[size,size],origin:'procedural',review:'unreviewed'};await saveAsset(record);await refreshAssets();download(record.blob,record.name+'.png');finish();}catch(e){if(busy)finish(e);else toast(e.message);}}
async function generateSound(){try{const kind=$('#audio-type').value,blob=makeAudio(kind);await saveAsset({id:crypto.randomUUID(),name:'SFX-'+kind,createdAt:new Date().toISOString(),type:'audio',blob,sha256:await sha256(blob),origin:'procedural',sampleRate:44100,review:'unreviewed'});await refreshAssets();download(blob,'FORGE-'+kind+'.wav');toast('Dźwięk zapisany w archiwum.');}catch(e){toast(e.message);}}
function beep(){if(!soundOn)return;const blob=makeAudio('beep'),url=URL.createObjectURL(blob),audio=new Audio(url);audio.onended=()=>URL.revokeObjectURL(url);audio.play().catch(()=>URL.revokeObjectURL(url));}
function scan(){if(world.mode!=='iss')return;const f=world.scan();$('#mission-text').textContent=f?`${f.name}. Przygotuj ${LABELS[f.kind].toLowerCase()} i zamontuj na stanowisku.`:'Podejdź bliżej pulsującego punktu (do 3,2 m) i skanuj ponownie.';$('#repair').disabled=!f;beep();}
async function repair(){try{const fault=world.discovered;if(!fault)throw Error('Najpierw podejdź i zeskanuj usterkę.');begin('Wytwarzanie części do symulacji');const p={kind:fault.kind,size:100,color:'#9be3bf'},object=build(p);updateProgress(40,'Geometria części gotowa.');const a=await archiveObject(object,{name:LABELS[p.kind]+' — misja ISS',spec:p,origin:'parametric',prompt:'Część demonstracyjna do misji ISS; nie jest projektem dopuszczonym do lotu.'});const mounted=await fromGLB(a.blob);mounted.scale.setScalar(10);world.repair(mounted);$('#mission-count').textContent=`${world.faults.filter(f=>f.done).length} / 3 napraw`;$('#repair').disabled=true;$('#mission-text').textContent=world.faults.every(f=>f.done)?'Misja ukończona. Wszystkie trzy demonstracyjne usterki usunięte.':'Część zamontowana. Odszukaj następne uszkodzenie.';finish();beep();}catch(e){if(busy)finish(e);else toast(e.message);}}
async function chat(text){log(text,true);const p=text.toLowerCase();if(/iss|orbit/.test(p)&&/le[cć]|lot|pole[cć]|przejd/.test(p)){world.setZone('iss');log('Jesteś w misji ISS. WASD lub przyciski kierunkowe: ruch.');return;}if(/wr[oó][cć]|ziemi/.test(p)){world.setZone('earth');return;}if(/skanuj|usterk/.test(p)){scan();return;}if(/napraw|zamontuj/.test(p)){await repair();return;}if(/obr[oó][cć]/.test(p)){if(!world.selected)throw Error('Wybierz obiekt do obrócenia.');const n=p.match(/-?\d+(?:[.,]\d+)?/)?.[0];world.selected.object.rotation.y+=T.MathUtils.degToRad(finite(n??45,-3600,3600));selectEntity(world.selected);persistWorld();log('Obiekt obrócony.');return;}if(/przenie[sś]/.test(p)){if(!world.selected)throw Error('Wybierz obiekt.');for(const axis of ['x','z']){const n=p.match(new RegExp(axis+'\\s*(-?\\d+(?:[.,]\\d+)?)'))?.[1];if(n)world.selected.object.position[axis]=finite(n.replace(',','.'),-100,100);}selectEntity(world.selected);persistWorld();return;}$('#prompt').value=text;$('#extra').value='';updatePrompt();setTab('create');await generate();}
async function init(){try{world=new World($('#viewport'),selectEntity,persistWorld);await refreshAssets();const saved=await loadWorld();if(saved?.entities?.length){for(const e of saved.entities){const a=assets.find(a=>a.id===e.assetId&&a.type==='model');if(!a)continue;world.add(await fromGLB(a.blob),{...e,transform:validateTransform(e.transform)});}for(const f of world.faults){f.done=!!saved.faults?.find(x=>x.kind===f.kind)?.done;f.marker.visible=!f.done;if(f.done){const o=build({kind:f.kind,size:1000,color:'#9be3bf'});o.position.copy(f.pos).add(new T.Vector3(0,.25,0));world.station.add(o);}}$('#mission-count').textContent=`${world.faults.filter(f=>f.done).length} / 3 napraw`;}else if(!assets.length){for(const [kind,x,z,size,color]of [['house',-9,-8,5000,'#9ca5e7'],['house',0,-8,5000,'#f0b77d'],['house',9,-8,5000,'#73cdb6'],['car',-4,0,2500,'#5dc6ad'],['excavator',7,7,2800,'#efb850'],['board',-5,8,5000,'#719bb5'],['tree',-15,-7,4000,'#409477'],['tree',15,-7,4000,'#409477']]){const object=build({kind,size:100,color}),a=await archiveObject(object,{name:LABELS[kind]+' — start',spec:{kind,size:100,color},origin:'starter',prompt:'Proceduralny obiekt startowy; wersja robocza.'});world.add(object,{id:crypto.randomUUID(),assetId:a.id,zone:'earth',transform:{x,y:0,z,rotation:0,scale:size/100}});}persistWorld();}updatePrompt();}catch(e){$('#render-error').hidden=false;$('#render-error').textContent='Nie udało się uruchomić świata 3D: '+e.message;log(e.message);}}
$$('[data-tab]').forEach(b=>b.onclick=()=>setTab(b.dataset.tab));$$('[data-preset]').forEach(b=>b.onclick=()=>{$('#prompt').value=b.dataset.preset;updatePrompt();});['prompt','extra','size','texture','purpose'].forEach(id=>$('#'+id).addEventListener('input',updatePrompt));$('#generate-form').onsubmit=e=>{e.preventDefault();generate();};$('#copy-prompt').onclick=async()=>{try{await navigator.clipboard.writeText($('#compiled').value);toast('Polecenie skopiowane.');}catch{download(new Blob([$('#compiled').value],{type:'text/plain'}),'FORGE-polecenie.txt');}};
$('#order-mode').onchange=()=>{$('#quantity').disabled=$('#order-mode').value==='single';if($('#quantity').disabled)$('#quantity').value=1;};$('#engine').onchange=()=>$('#engine-note').textContent=$('#engine').value==='local'?'Parametryczne bryły i schematy: zazwyczaj kilka sekund. Wymiar z opisu ma pierwszeństwo.':'Pełna rekonstrukcja z opisu i zdjęć. Czas zależy od modelu, obciążenia i kontroli jakości; estymacja pojawi się, gdy serwer ją poda.';
$('#photo').onchange=()=>{if(photoURL)URL.revokeObjectURL(photoURL);const f=$('#photo').files[0];$('#photo-preview').hidden=!f;if(f){photoURL=URL.createObjectURL(f);$('#photo-preview').src=photoURL;$('#engine').value='oracle';$('#engine').onchange();}};
$('#hide-progress').onclick=()=>$('#progress-dialog').close();$('#close-progress').onclick=()=>$('#progress-dialog').close();$('#stop-queue').onclick=()=>{stop=true;$('#progress-note').textContent='Kolejne kopie zatrzymane. Aktywne zadanie Oracle kończy pracę i zostanie zapisane.';};$('#connection').onclick=()=>$('#connection-dialog').showModal();$('#close-connection').onclick=()=>$('#connection-dialog').close();$('#connect-form').onsubmit=async e=>{e.preventDefault();try{const h=await oracle.connect($('#api-url').value,$('#api-token').value);$('#api-token').value='';$('#connection-status').textContent=`Połączono. Oracle ${h.connectorVersion??''}. ${h.ready?'Generator gotowy.':'Generator wymaga konfiguracji.'}`;$('#connection').textContent='Oracle · połączony';const pending=localStorage.getItem('forge-pending-job');if(pending&&!busy){$('#connection-dialog').close();begin('Wznawianie podglądu zlecenia');activeJob=pending;watchJob(pending).catch(finish);}}catch(e){$('#connection-status').textContent=e.message;}};$('#disconnect').onclick=()=>{oracle.disconnect();$('#api-token').value='';$('#connection').textContent='Oracle · połącz';$('#connection-status').textContent='Rozłączono.';};
$('#home-world').onclick=()=>world.setZone('earth');$('#iss-world').onclick=()=>world.setZone('iss');$('#walk').onclick=()=>{world.controlled=null;world.toggleWalk();};$('#control').onclick=()=>{if(!world.selected)return toast('Wybierz pojazd lub postać.');world.controlled=world.selected.object;world.toggleWalk(true);toast('Sterowanie WASD / strzałkami. Esc wraca do edytora.');};$('#sound').onclick=()=>{soundOn=!soundOn;$('#sound').textContent=soundOn?'Dźwięk: wł.':'Dźwięk: wył.';beep();};$('#clay').onclick=()=>{world.setMaterial(!world.clay,world.wire);$('#clay').classList.toggle('active',world.clay);};$('#wire').onclick=()=>{world.setMaterial(world.clay,!world.wire);$('#wire').classList.toggle('active',world.wire);};$('#focus').onclick=()=>world.focus();$('#export-glb').onclick=()=>exportSelected('glb');$('#export-stl').onclick=()=>exportSelected('stl');
$('#apply-transform').onclick=()=>{try{if(!world.selected)throw Error('Wybierz obiekt.');const t=validateTransform({x:$('#pos-x').value,z:$('#pos-z').value,rotation:$('#rotation').value,scale:$('#scale').value});world.selected.object.position.set(t.x,t.y,t.z);world.selected.object.rotation.y=T.MathUtils.degToRad(t.rotation);world.selected.object.scale.setScalar(t.scale);persistWorld();toast('Położenie zapisane.');}catch(e){toast(e.message);}};$('#remove-world').onclick=()=>{const e=world.selected;if(!e)return;world.controlled=null;e.object.removeFromParent();world.entities.delete(e.id);world.selected=null;persistWorld();$('#selected-name').textContent='Wybierz obiekt';toast('Usunięto ze świata. Model pozostaje w archiwum.');};
$$('[data-key]').forEach(b=>{b.onpointerdown=e=>{e.preventDefault();b.setPointerCapture(e.pointerId);if(!world.walking)world.toggleWalk(true);world.keys.add(b.dataset.key);};b.onpointerup=b.onpointercancel=b.onlostpointercapture=()=>world.keys.delete(b.dataset.key);});$('#scan').onclick=scan;$('#repair').onclick=repair;document.addEventListener('keydown',e=>{if(e.code==='KeyE'&&!e.target.closest('input,textarea,select,dialog'))scan();});$('#chat-form').onsubmit=async e=>{e.preventDefault();const text=$('#chat-input').value;$('#chat-input').value='';try{await chat(text);}catch(e){log(e.message);}};
$('#dictate').onclick=()=>{const Speech=window.SpeechRecognition??window.webkitSpeechRecognition;if(!Speech)return toast('Ta przeglądarka nie obsługuje dyktowania. Użyj mikrofonu na klawiaturze telefonu.');const s=new Speech();s.lang='pl-PL';s.interimResults=false;s.onresult=e=>{$('#chat-input').value=e.results[0][0].transcript;toast('Sprawdź rozpoznane polecenie i kliknij Wykonaj.');};s.onerror=e=>toast('Dyktowanie: '+e.error);s.start();};$('#backup').onclick=backup;$('#restore').onclick=()=>$('#restore-input').click();$('#restore-input').onchange=e=>restore(e.target.files[0]);$('#import-glb').onchange=e=>importFiles([...e.target.files]);$('#sync-originals').onclick=syncOriginals;$('#make-texture').onclick=generateTexture;$('#make-audio').onclick=generateSound;
$('#bom').onclick=()=>{if(!basket.size)return toast('Dodaj modele do zamówienia.');if(!$('#check-geometry').checked||!$('#check-texture').checked)return toast('Sprawdź osobno geometrię i tekstury każdego modelu.');const rows=[['model','asset_id','sha256','liczba','x_mm','y_mm','z_mm','material','kolor','region','cena_za_kg','status']];for(const [id,n]of basket){const a=assets.find(a=>a.id===id),d=a.report.dimensions;rows.push([a.name,id,a.sha256,n,d.x.toFixed(2),d.y.toFixed(2),d.z.toFixed(2),$('#material').value,$('#finish').value,$('#region').value,'do potwierdzenia','roboczy — weryfikacja produkcji wymagana']);}download(new Blob(['\ufeff'+rows.map(r=>r.map(escapeCSV).join(';')).join('\r\n')],{type:'text/csv;charset=utf-8'}),'FORGE-zamowienie-B2B.csv');};
init();
