import { z } from 'zod'
import type { IntegrationHealth } from '../types/core'
import { createCandidate, executeGame, promoteCandidate, rollbackCandidate, runTournament, type Tournament } from '../integrations/cube/lab'
import { analyzeVisualReadability, decideVisualChange, proposeVisualChange, runVisualQa } from '../integrations/visual/workflow'
import { createResearchStation, findObservations, getElevationProfile, searchLocation, setAreaOfInterest, setStationTimespan } from '../integrations/terra/adapter'
import {
  HAZARD_LABELS,
  HAZARD_TYPES,
  analyzeMultiyearImagery,
  draftPreliminaryAlert,
  evaluateGroundVerification,
  proposeRecoveryOptions,
  rankCausalHypotheses,
  retrieveMultiyearImagery,
  runHazardInvestigation,
} from '../integrations/terra/hazardInvestigation'
import { findGlobalWaterAnalogues, inspectLocalHydrologyContext, inspectTest001Evidence, resolveReferenceDataset, runLabMcpTest001 } from '../integrations/terra/labmcp'
import { RESEARCH_STATION_PRESETS } from '../data/researchStations'
import {
  createAssetSpecification,
  prepareB2bRfq,
  prepareCodexAssetBrief,
  prepareShopifyDraft,
  runAssetQualityGate,
  shopifyCartNotConnected,
  supplierSubmissionNotConnected,
  type AssetConfiguration,
} from '../integrations/commerce/productLab'
import { generateProceduralAssetBundle, proceduralAssetManifest } from '../integrations/commerce/proceduralAssets'
import { verifyScientificEvidence } from '../verification/engine'
export type ToolDomain='terra'|'cube'|'visual'|'commerce'|'verification'|'system'
export interface WebMcpToolDefinition{name:string;domain:ToolDomain;description:string;inputSchema:Record<string,unknown>;outputSchema:Record<string,unknown>;readOnly:boolean;requiresApproval:boolean;connectionStatus:IntegrationHealth;verificationPolicy:string;execute:(input:unknown)=>Promise<unknown>}
type Base=Omit<WebMcpToolDefinition,'inputSchema'|'outputSchema'|'connectionStatus'|'verificationPolicy'> & {inputSchema?:Record<string,unknown>;outputSchema?:Record<string,unknown>;connectionStatus?:IntegrationHealth;verificationPolicy?:string}
const schema={type:'object',additionalProperties:true};const ok=(data:unknown,verification:'PASS'|'WARNING'|'FAIL'|'INSUFFICIENT_DATA'='PASS')=>({state:verification==='PASS'?'PASS':verification==='FAIL'?'FAIL':'WARNING',data,verification,provenance:(data as {provenance?:unknown})?.provenance??[]})
const safe=<T>(s:z.ZodType<T>,fn:(v:T)=>unknown|Promise<unknown>)=>async(input:unknown)=>{const p=s.safeParse(input);if(!p.success)return {state:'FAIL',verification:'FAIL',error:p.error.issues.map(i=>i.message).join('; '),provenance:[]};try{return await fn(p.data)}catch(e){return {state:'NOT_CONNECTED',verification:'INSUFFICIENT_DATA',error:e instanceof Error?e.message:'Dependency unavailable',provenance:[]}}}
const empty=z.object({}).passthrough(),coords=z.object({lat:z.number().min(-90).max(90),lon:z.number().min(-180).max(180)})
const hazardType=z.enum(HAZARD_TYPES)
const hazardInput=z.object({regionQuery:z.string().min(2).max(160),latitude:z.number().min(-90).max(90).optional(),longitude:z.number().min(-180).max(180).optional(),radiusKm:z.number().min(1).max(500),startYear:z.number().int().min(1972).max(new Date().getUTCFullYear()),endYear:z.number().int().min(1972).max(new Date().getUTCFullYear()),season:z.enum(['all','spring','summer','autumn','winter']),hazardTypes:z.array(hazardType).min(1).max(8),depth:z.enum(['screening','deep']),timelineMode:z.enum(['representative','annual']),spatialMode:z.enum(['overview','regional-patrol']).optional(),patrolTileCount:z.number().int().min(4).max(20).optional(),patrolFrameWidthKm:z.number().min(0.5).max(2).optional(),referenceQuery:z.string().min(2).max(120).optional(),caseId:z.literal('test-001-forest-pond-kuchnia').optional(),focusLatitude:z.number().min(-90).max(90).optional(),focusLongitude:z.number().min(-180).max(180).optional(),focusRadiusKm:z.number().min(0.1).max(50).optional()})
const assetConfigInput=z.object({track:z.enum(['cube-asset','terra-station']),stationId:z.enum(['arctic','sahara','ocean','earth-space']),assetKind:z.enum(['figurine','board','texture-pack','station-shell']),boardPreset:z.enum(['cube-512','classic-mono','lab-ledcolor']),piecePreset:z.enum(['czech-facet','classic','lab-ledcolor','earth-guardian']),material:z.string().min(2).max(240),texture:z.string().min(2).max(500),primaryColor:z.string().regex(/^#[0-9a-f]{6}$/i),secondaryColor:z.string().regex(/^#[0-9a-f]{6}$/i),ledIntensity:z.number().min(0).max(100),scaleMm:z.number().min(20).max(500),prompt:z.string().min(20).max(2000)})
const labOutputSchema={type:'object',properties:{state:{type:'string',enum:['PASS','WARNING','FAIL','NOT_CONNECTED']},verification:{type:'string',enum:['PASS','WARNING','FAIL','INSUFFICIENT_DATA']},data:{type:'object',additionalProperties:true},error:{type:'string'},provenance:{type:'array',items:{type:'object',additionalProperties:true}}},required:['state','verification','provenance'],additionalProperties:false}
const tools:Base[]=[
 {name:'get_forgemcp_status',domain:'system',description:'Return local runtime status.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok({status:'READY',timestamp:new Date().toISOString()}))},
 {name:'list_capabilities',domain:'system',description:'List bounded capabilities.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok(webmcpTools.map(t=>({name:t.name,domain:t.domain,readOnly:t.readOnly,requiresApproval:t.requiresApproval}))))},
 {name:'get_integration_status',domain:'system',description:'Report browser integration boundaries without probing hidden services.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok({forge:'CONNECTED',cubeEngine:'CONNECTED_LOCAL_PINNED',terra:'PUBLIC_NETWORK_REQUIRED',localProceduralExporter:'CONNECTED_LOCAL',shopify:'NOT_CONNECTED',supplierDirectory:'NOT_CONNECTED',webmcp:'BROWSER_DEPENDENT'}))},
 {name:'search_location',domain:'terra',description:'Resolve a place with public OpenStreetMap Nominatim.',readOnly:true,requiresApproval:false,execute:safe(z.object({query:z.string().min(2).max(120)}),async v=>ok({results:await searchLocation(v.query),provenance:[{provider:'OpenStreetMap',dataset:'Nominatim',query:v.query}]}))},
 {name:'set_area_of_interest',domain:'terra',description:'Validate and bound a WGS84 AOI.',readOnly:true,requiresApproval:false,execute:safe(coords.extend({name:z.string().min(1),radiusKm:z.number().min(1).max(250)}),v=>ok(setAreaOfInterest(v)))},
 {name:'create_research_station',domain:'terra',description:'Create a browser-run research station.',readOnly:false,requiresApproval:false,execute:safe(coords.extend({name:z.string().min(1),radiusKm:z.number().min(1).max(250)}),v=>ok(createResearchStation(v.name,v)))},
 {name:'set_station_timespan',domain:'terra',description:'Set an ISO date range.',readOnly:false,requiresApproval:false,execute:safe(z.object({stationId:z.string(),startDate:z.iso.date(),endDate:z.iso.date()}),v=>ok(setStationTimespan(v.stationId,v.startDate,v.endDate)))},
 {name:'find_observations',domain:'terra',description:'Query real NASA EONET events near an AOI.',readOnly:true,requiresApproval:false,execute:safe(coords.extend({days:z.number().int().min(1).max(60)}),async v=>{const d=await findObservations(v.lat,v.lon,v.days);return ok(d,d.observations.length?'WARNING':'INSUFFICIENT_DATA')})},
 {name:'compare_dates',domain:'terra',description:'Compare supplied observation counts without inferring cause.',readOnly:true,requiresApproval:false,execute:safe(z.object({dateA:z.iso.date(),countA:z.number().int().nonnegative(),dateB:z.iso.date(),countB:z.number().int().nonnegative()}),v=>ok({classification:'OBSERVATION',difference:v.countB-v.countA,...v,uncertainty:'Event-count comparison only.'},'WARNING'))},
 {name:'get_elevation_profile',domain:'terra',description:'Fetch public Copernicus DEM samples via Open-Meteo.',readOnly:true,requiresApproval:false,execute:safe(coords,async v=>{const d=await getElevationProfile(v.lat,v.lon);return d.state==='OBSERVATION'?ok(d,'WARNING'):{state:d.state,verification:'INSUFFICIENT_DATA',error:d.error,provenance:[]}})},
 {name:'plan_hazard_investigation',domain:'terra',description:'Validate a user-selected region, multi-year period and hazard classes, then return the real agent/tool plan without claiming that retrieval already ran.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',additionalProperties:true},outputSchema:labOutputSchema,execute:safe(hazardInput,v=>ok({classification:'HYPOTHESIS',area:{regionQuery:v.regionQuery,latitude:v.latitude??null,longitude:v.longitude??null,radiusKm:v.radiusKm},period:{startYear:v.startYear,endYear:v.endYear,season:v.season},hazards:v.hazardTypes.map(item=>({id:item,label:HAZARD_LABELS[item]})),depth:v.depth,timelineMode:v.timelineMode,spatialMode:v.spatialMode??'overview',regionalPatrol:v.spatialMode==='regional-patrol'?{tileCount:v.patrolTileCount??20,frameWidthKm:v.patrolFrameWidthKm??1,fullCoverage:false}:null,tools:['search_location when coordinates are absent','analyze_multiyear_imagery','retrieve_multiyear_imagery',...(v.spatialMode==='regional-patrol'?['inspect_regional_patrol_tiles']:[]),'get_elevation_profile','find_observations','find_global_water_analogues for water hazards','rank_causal_hypotheses','draft_preliminary_risk_alert','propose_recovery_options','verify_evidence'],policy:'This is a plan only. No source has been retrieved yet.'},'WARNING'))},
 {name:'analyze_multiyear_imagery',domain:'terra',description:'Ask the public Terra evidence Worker to visually inspect representative official/public NASA, USGS and Copernicus imagery for a selected AOI and period.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',additionalProperties:true},outputSchema:labOutputSchema,execute:safe(hazardInput.extend({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)}),async v=>{const d=await analyzeMultiyearImagery(v,v.latitude,v.longitude);return ok(d,d.ai_visual_image_count?'WARNING':'INSUFFICIENT_DATA')})},
 {name:'retrieve_multiyear_imagery',domain:'terra',description:'Retrieve one explicit official Landsat browse or labelled NASA GIBS fallback slot per requested year; returned gallery images are not falsely reported as model-inspected.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',additionalProperties:true},outputSchema:labOutputSchema,execute:safe(hazardInput.extend({latitude:z.number().min(-90).max(90),longitude:z.number().min(-180).max(180)}),async v=>{const d=await retrieveMultiyearImagery(v,v.latitude,v.longitude);return ok(d,d.slots.some(item=>item.status==='image')?'WARNING':'INSUFFICIENT_DATA')})},
 {name:'rank_causal_hypotheses',domain:'terra',description:'Create competing causal hypotheses and the measurements needed to test them; never convert an analogue or visual pattern into local causal proof.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{hazardTypes:{type:'array',items:{type:'string'}},recordedAnomaly:{type:'boolean'}},required:['hazardTypes'],additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({hazardTypes:z.array(hazardType).min(1).max(8),recordedAnomaly:z.boolean().default(false)}),v=>ok({classification:'HYPOTHESIS',hypotheses:rankCausalHypotheses(v.hazardTypes,[],v.recordedAnomaly),causeEstablished:false},'WARNING'))},
 {name:'draft_preliminary_risk_alert',domain:'terra',description:'Draft, but never send, a preliminary environmental risk alert that preserves uncertainty and requires human approval.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',additionalProperties:true},outputSchema:labOutputSchema,execute:safe(z.object({region:z.string().min(2).max(160),hazardTypes:z.array(hazardType).min(1).max(8),hasRecordedAnomaly:z.boolean().default(false),visualImageCount:z.number().int().nonnegative().max(50),signals:z.array(z.object({hazardType,matchedText:z.string().min(1).max(2000)})).max(8).default([])}),v=>ok(draftPreliminaryAlert({region:v.region,hazards:v.hazardTypes,hasRecordedAnomaly:v.hasRecordedAnomaly,visualImageCount:v.visualImageCount,signals:v.signals.map(item=>({...item,meaning:'TEXT_SCREENING_CANDIDATE_NOT_CAUSAL_PROOF' as const}))}),'WARNING'))},
 {name:'propose_recovery_options',domain:'terra',description:'Return conditional monitoring, repair and regeneration options with engineering, authority and permit gates.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{hazardTypes:{type:'array',items:{type:'string'}}},required:['hazardTypes'],additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({hazardTypes:z.array(hazardType).min(1).max(8)}),v=>ok({classification:'CONDITIONAL_OPTIONS',options:proposeRecoveryOptions(v.hazardTypes),automaticIntervention:false},'WARNING'))},
 {name:'record_ground_verification',domain:'verification',description:'Evaluate a precisely scoped field verification record. VERIFIED_FINDING requires independent measurements, a public source, a responsible expert and literal human approval.',readOnly:false,requiresApproval:true,inputSchema:{type:'object',additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({verificationDate:z.iso.date(),method:z.string().min(10).max(2000),finding:z.string().min(10).max(4000),sourceUrl:z.url().refine(value=>value.startsWith('https://'),'HTTPS source required'),independentlyVerified:z.boolean(),measurementsAttached:z.boolean(),responsibleExpert:z.string().min(3).max(240),humanApproved:z.literal(true)}),v=>ok(evaluateGroundVerification(v),v.independentlyVerified&&v.measurementsAttached?'PASS':'WARNING'))},
 {name:'run_hazard_investigation',domain:'terra',description:'Run the complete user-selected multi-agent environmental investigation: geocoding, multi-year official imagery, visual analysis, DEM/events, analogues, causal hypotheses, an unsent alert draft, recovery options and verification gates.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',additionalProperties:true},outputSchema:labOutputSchema,execute:safe(hazardInput,async v=>{const d=await runHazardInvestigation(v);return ok(d,d.verification.state)})},
 {name:'inspect_test_001_evidence',domain:'terra',description:'Retrieve and validate the recorded public TEST 001 pond measurement and separate author field report without claiming a fresh EO run.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{},additionalProperties:false},outputSchema:labOutputSchema,execute:safe(empty,async()=>ok(await inspectTest001Evidence(),'WARNING'))},
 {name:'resolve_reference_dataset',domain:'terra',description:'Resolve candidate records for a named reference such as Toruń without silently selecting an incompatible dataset.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{query:{type:'string',minLength:2,maxLength:120,default:'Toruń'}},additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({query:z.string().min(2).max(120).default('Toruń')}),async v=>ok(await resolveReferenceDataset(v.query),'INSUFFICIENT_DATA'))},
 {name:'find_global_water_analogues',domain:'terra',description:'Search the live public validated hydrology catalogues and return deterministic context-only analogues.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{limit:{type:'integer',minimum:12,maximum:16,default:12},terms:{type:'array',items:{type:'string'},maxItems:20}},additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({limit:z.number().int().min(12).max(16).default(12),terms:z.array(z.string().min(2).max(60)).max(20).optional()}),async v=>ok(await findGlobalWaterAnalogues(v.limit,v.terms),'WARNING'))},
 {name:'inspect_local_hydrology_context',domain:'terra',description:'Return curated, source-linked Lake Kuchnia connectivity references without claiming live page/PDF revalidation or current flow.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{},additionalProperties:false},outputSchema:labOutputSchema,execute:safe(empty,()=>ok({items:inspectLocalHydrologyContext(),retrievalMode:'CURATED_SOURCE_REFERENCE'},'WARNING'))},
 {name:'run_labmcp_test_001',domain:'terra',description:'Run the bounded TEST 001 LabMCP workflow over real recorded evidence, the Toruń resolver, documentary connectivity context and global analogue catalogues.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{referenceQuery:{type:'string',minLength:2,maxLength:120,default:'Toruń'},analogueLimit:{type:'integer',minimum:12,maximum:16,default:12}},additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({referenceQuery:z.string().min(2).max(120).default('Toruń'),analogueLimit:z.number().int().min(12).max(16).default(12)}),async v=>ok(await runLabMcpTest001(v),'WARNING'))},
 {name:'inspect_hazard_signals',domain:'terra',description:'Inspect TEST 001 competing hazard hypotheses while keeping recorded anomaly, current risk and causation separate.',readOnly:true,requiresApproval:false,inputSchema:{type:'object',properties:{referenceQuery:{type:'string',minLength:2,maxLength:120,default:'Toruń'}},additionalProperties:false},outputSchema:labOutputSchema,execute:safe(z.object({referenceQuery:z.string().min(2).max(120).default('Toruń')}),async v=>{const d=await runLabMcpTest001({referenceQuery:v.referenceQuery,analogueLimit:12});return ok({environmentalState:d.environmentalState,signalState:d.signalState,hypothesisMatrix:d.hypothesisMatrix,verification:d.verification,provenance:d.provenance},'WARNING')})},
 {name:'verify_evidence',domain:'verification',description:'Apply deterministic provenance/sufficiency checks.',readOnly:true,requiresApproval:false,execute:safe(z.object({observations:z.number().int().nonnegative(),hasProvenance:z.boolean()}),v=>ok(verifyScientificEvidence(v.observations,v.hasProvenance),v.observations&&v.hasProvenance?'WARNING':'INSUFFICIENT_DATA'))},
 {name:'generate_research_report',domain:'terra',description:'Package supplied evidence without inventing findings.',readOnly:true,requiresApproval:false,execute:safe(z.object({location:z.string(),classification:z.enum(['OBSERVATION','ANOMALY','HYPOTHESIS','PRELIMINARY_RISK_ALERT','VERIFIED_FINDING','INSUFFICIENT_DATA']),indicators:z.array(z.string()),sources:z.array(z.string()),uncertainty:z.array(z.string())}),v=>ok({...v,generatedAt:new Date().toISOString(),groundVerificationRequired:true},v.indicators.length?'WARNING':'INSUFFICIENT_DATA'))},
 {name:'create_ai_candidate',domain:'cube',description:'Create a deterministic capture-policy candidate.',readOnly:false,requiresApproval:false,execute:safe(z.object({id:z.string().min(1).optional()}),v=>ok(createCandidate(v.id)))},
 {name:'start_selfplay',domain:'cube',description:'Execute one legal deterministic Cube game.',readOnly:false,requiresApproval:false,execute:safe(z.object({seed:z.number().int().default(42),maxPlies:z.number().int().min(2).max(80).default(40)}),v=>ok(executeGame(v.seed,'candidate-capture-v1','baseline-v1',v.maxPlies)))},
 {name:'run_ai_tournament',domain:'cube',description:'Execute paired seeded candidate-v-baseline games.',readOnly:false,requiresApproval:false,execute:safe(z.object({candidateId:z.string(),games:z.number().int().min(2).max(8),seed:z.number().int()}),v=>ok(runTournament(v.candidateId,v.games,v.seed),'WARNING'))},
 {name:'inspect_game',domain:'cube',description:'Inspect a replay record.',readOnly:true,requiresApproval:false,execute:safe(z.object({game:z.unknown()}),v=>ok(v.game))},
 {name:'analyze_blunders',domain:'cube',description:'Report deterministic material-loss proxy.',readOnly:true,requiresApproval:false,execute:safe(z.object({materialLossProxy:z.number()}),v=>ok(v))},
 {name:'evaluate_candidate',domain:'cube',description:'Evaluate explicit tournament gates.',readOnly:true,requiresApproval:false,execute:safe(z.object({tournament:z.unknown()}),v=>ok(v.tournament))},
 {name:'promote_ai_candidate',domain:'cube',description:'Promote only after gates and explicit approval.',readOnly:false,requiresApproval:true,execute:safe(z.object({candidateId:z.string(),tournament:z.unknown(),humanApproved:z.literal(true)}),v=>ok(promoteCandidate(v.candidateId,v.tournament as Tournament,v.humanApproved)))},
 {name:'rollback_ai_candidate',domain:'cube',description:'Reversibly restore prior policy with approval.',readOnly:false,requiresApproval:true,execute:safe(z.object({candidateId:z.string(),humanApproved:z.literal(true)}),v=>ok(rollbackCandidate(v.candidateId,v.humanApproved)))},
 {name:'analyze_visual_readability',domain:'visual',description:'Analyze current visual configuration.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok(analyzeVisualReadability(),'WARNING'))},
 {name:'propose_visual_change',domain:'visual',description:'Create a reversible preview diff.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok(proposeVisualChange(),'WARNING'))},
 {name:'preview_visual_change',domain:'visual',description:'Return before/after without live mutation.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok(proposeVisualChange(),'WARNING'))},
 {name:'run_visual_qa',domain:'visual',description:'Run deterministic configuration QA.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok(runVisualQa()))},
 {name:'approve_visual_change',domain:'visual',description:'Record approval; never mutate upstream.',readOnly:false,requiresApproval:true,execute:safe(z.object({humanApproved:z.literal(true)}),()=>ok(decideVisualChange('APPROVE')))},
 {name:'reject_visual_change',domain:'visual',description:'Reject and discard preview.',readOnly:false,requiresApproval:false,execute:safe(empty,()=>ok(decideVisualChange('REJECT'),'WARNING'))},
 {name:'list_asset_station_presets',domain:'commerce',description:'List the four versioned Terra station concepts available as Game Studio material systems.',readOnly:true,requiresApproval:false,execute:safe(empty,()=>ok(RESEARCH_STATION_PRESETS.map(item=>({id:item.id,name:item.name,subtitle:item.subtitle,status:item.status,material:item.material,texture:item.texture,truthBoundary:item.truthBoundary}))))},
 {name:'configure_3d_asset',domain:'commerce',description:'Create a deterministic, versioned asset specification. This does not generate a mesh or texture archive.',readOnly:false,requiresApproval:false,execute:safe(assetConfigInput,v=>ok(createAssetSpecification(v as AssetConfiguration),'WARNING'))},
 {name:'generate_procedural_asset_preview',domain:'commerce',description:'Return the bounded browser preview contract for an asset concept; never claim that a GLB, STL or manufacturing file was generated.',readOnly:true,requiresApproval:false,execute:safe(assetConfigInput,v=>{const specification=createAssetSpecification(v as AssetConfiguration);return ok({status:'PROCEDURAL_PREVIEW',specification,generatedModelFile:false,manufacturingReady:false},'WARNING')})},
 {name:'generate_procedural_asset_files',domain:'commerce',description:'Generate low-poly glTF model data and deterministic PNG bytes in memory, then return the bounded QA/download manifest. The UI performs explicit file downloads; nothing is persisted by this tool.',readOnly:true,requiresApproval:false,execute:safe(assetConfigInput,v=>{const specification=createAssetSpecification(v as AssetConfiguration);return ok(proceduralAssetManifest(generateProceduralAssetBundle(specification)),'WARNING')})},
 {name:'run_asset_qa',domain:'commerce',description:'Run deterministic configuration QA and disclose missing mesh, UV, PBR, printability and physical tests.',readOnly:true,requiresApproval:false,execute:safe(assetConfigInput,v=>{const specification=createAssetSpecification(v as AssetConfiguration);return ok({specificationId:specification.id,...runAssetQualityGate(specification)},'WARNING')})},
 {name:'prepare_codex_asset_prompt',domain:'commerce',description:'Prepare an explicit Codex agent handoff from a human asset prompt without claiming that external generation ran.',readOnly:true,requiresApproval:false,execute:safe(assetConfigInput,v=>ok(prepareCodexAssetBrief(v.prompt,v as AssetConfiguration),'WARNING'))},
 {name:'prepare_shopify_product_draft',domain:'commerce',description:'Prepare an unpublished local product brief for later Shopify field mapping. No ProductCreateInput, store write, variant or checkout is created.',readOnly:false,requiresApproval:false,execute:safe(assetConfigInput,v=>ok(prepareShopifyDraft(createAssetSpecification(v as AssetConfiguration)),'WARNING'))},
 {name:'create_shopify_test_cart',domain:'commerce',description:'Guarded Shopify cart boundary. It cannot return a fake checkout and remains NOT_CONNECTED until a real store variant is authorized.',readOnly:false,requiresApproval:true,connectionStatus:'NOT_CONNECTED',execute:safe(z.object({specificationId:z.string().min(8),humanApproved:z.literal(true)}),()=>shopifyCartNotConnected())},
 {name:'prepare_b2b_rfq',domain:'commerce',description:'Prepare an unsent manufacturing request from the asset specification; Shopify is not represented as a supplier search engine.',readOnly:false,requiresApproval:false,execute:safe(assetConfigInput,v=>ok(prepareB2bRfq(createAssetSpecification(v as AssetConfiguration)),'WARNING'))},
 {name:'submit_b2b_rfq',domain:'commerce',description:'Guarded supplier-send boundary. No request is sent until a real recipient is verified and separately authorized.',readOnly:false,requiresApproval:true,connectionStatus:'NOT_CONNECTED',execute:safe(z.object({specificationId:z.string().min(8),recipientId:z.string().min(2),humanApproved:z.literal(true)}),()=>supplierSubmissionNotConnected())},
]
export const webmcpTools:WebMcpToolDefinition[]=tools.map(t=>({...t,inputSchema:t.inputSchema??schema,outputSchema:t.outputSchema??schema,connectionStatus:t.connectionStatus??'CONNECTED',verificationPolicy:t.verificationPolicy??(t.requiresApproval?'Automated gates plus explicit human approval':'Validated structured status and provenance')}))
export const getTool=(name:string)=>webmcpTools.find(t=>t.name===name)
