'use strict';
const $=id=>document.getElementById(id);
let product='Szachownica i figury';let refURL;
function save(name,value){const url=URL.createObjectURL(new Blob([JSON.stringify(value,null,2)],{type:'application/json'}));const a=document.createElement('a');a.href=url;a.download=name;a.click();setTimeout(()=>URL.revokeObjectURL(url),1000)}
document.querySelectorAll('[data-view]').forEach(button=>button.addEventListener('click',()=>{document.querySelectorAll('[data-view]').forEach(b=>b.classList.toggle('active',b===button));$('model-image').src='/assets/model-'+button.dataset.view+'.webp';$('model-image').alt='Render modelu: '+button.textContent}));
$('reference').addEventListener('change',()=>{if(refURL)URL.revokeObjectURL(refURL);const f=$('reference').files[0];if(!f){$('reference-preview').hidden=true;return}if(f.size>15*1024*1024){$('brief-status').textContent='Wybierz obraz mniejszy niż 15 MB.';$('reference').value='';$('reference-preview').hidden=true;return}refURL=URL.createObjectURL(f);$('reference-preview').src=refURL;$('reference-preview').hidden=false});
$('brief-form').addEventListener('submit',e=>{e.preventDefault();const prompt=$('prompt').value.trim();if(!prompt){$('prompt').focus();return}save('FORGE-projekt.json',{schema:'forge-public-brief-v1',prompt,purpose:$('purpose').value,reference_filename:$('reference').files[0]?.name||null,reference_attached:false,generation_started:false,created_at:new Date().toISOString()});$('brief-status').textContent='Opis projektu pobrany. Dołącz oryginalną grafikę, przekazując zlecenie operatorowi. Model nie został jeszcze wygenerowany.'});
document.querySelectorAll('[data-product]').forEach(b=>b.addEventListener('click',()=>{product=b.dataset.product;$('quote-title').textContent=product;$('quote-form').scrollIntoView({behavior:'smooth',block:'center'})}));
function estimate(){const rate=$('rate').value;const mass=Number($('mass').value),finish=Number($('finish').value);if(rate===''||!Number.isFinite(Number(rate))||Number(rate)<0||mass<=0||finish<0){$('quote-price').textContent='Cena wymaga cennika wykonawcy.';return null}const n=mass*Number(rate)+finish;$('quote-price').textContent=n.toLocaleString('pl-PL',{style:'currency',currency:'EUR'})+' · szacunek';return n}
['mass','rate','finish'].forEach(id=>$(id).addEventListener('input',estimate));
$('quote-form').addEventListener('submit',e=>{e.preventDefault();save('FORGE-wycena-B2B.json',{schema:'forge-b2b-brief-v1',product,prompt:$('prompt').value.trim(),material:$('material').value,process:$('process').value,mass_kg:Number($('mass').value),colors:Number($('colors').value),rate_eur_per_kg:$('rate').value===''?null:Number($('rate').value),finishing_eur:Number($('finish').value),estimate_eur:estimate(),currency:'EUR',status:'draft_not_sent',tax_and_shipping_included:false});$('quote-status').textContent='Specyfikacja pobrana. Nie wysłano zamówienia ani płatności.'});
fetch('/assets/release.json').then(r=>r.ok?r.json():null).then(r=>{if(!r)return;if(r.model)$('model-name').textContent=r.model;if(r.queen)$('queen-section').hidden=false;if(r.comparison)$('comparison-caption').textContent=r.comparison}).catch(()=>{});
