import type { AgentDefinition } from '../types/core'

export const agentRegistry: AgentDefinition[] = [
  {
    id: 'research-coordinator',
    name: 'Research Coordinator',
    domain: 'terra',
    responsibility: 'Coordinates Terra AOI and tool chain execution.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Evidence verifier review required for alerts'],
  },
  {
    id: 'source-scout',
    name: 'Source Scout',
    domain: 'terra',
    responsibility: 'Finds external data sources and observations.',
    allowedToolCategories: ['terra'],
    readWrite: 'read',
    verificationRequirements: ['Provider provenance required'],
  },
  {
    id: 'eo-analyst',
    name: 'EO Analyst',
    domain: 'terra',
    responsibility: 'Assesses Earth observation indicators.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Confidence and uncertainty reporting required'],
  },
  {
    id: 'copernicus-esa-source-agent',
    name: 'Copernicus/ESA Source Agent (our agent)',
    domain: 'terra',
    responsibility: 'Uses public Copernicus/ESA sources while explicitly avoiding any claim that this agent is operated or endorsed by ESA.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Mission, acquisition/source and visual-versus-metadata status must stay explicit'],
  },
  {
    id: 'multiyear-imagery-analyst',
    name: 'Multi-year Imagery Analyst',
    domain: 'terra',
    responsibility: 'Compares representative images across years and keeps the annual catalogue separate from images actually inspected by the model.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Report ai_visual_image_count and missing years; never claim that every catalogue slot was inspected'],
  },
  {
    id: 'terrain-change-analyst',
    name: 'Terrain Change Analyst',
    domain: 'terra',
    responsibility: 'Investigates erosion, deposition, earthworks and relief-change hypotheses using EO and DEM context.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['DEM raster context never substitutes for surveyed change or geotechnical inspection'],
  },
  {
    id: 'flood-snow-hazard-analyst',
    name: 'Flood / Snow Hazard Analyst',
    domain: 'terra',
    responsibility: 'Screens flood, snow-avalanche and landslide patterns and specifies the responsible field services needed to verify them.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['No operational warning or access restriction without the competent emergency service'],
  },
  {
    id: 'causal-hypothesis-analyst',
    name: 'Causal Hypothesis Analyst',
    domain: 'terra',
    responsibility: 'Maintains competing explanations and the measurements that could support or weaken each one.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Visible correlation and global analogy are never local causal proof'],
  },
  {
    id: 'hazard-agent',
    name: 'Hazard Agent',
    domain: 'terra',
    responsibility: 'Produces preliminary risk alerts only.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Never output verified finding without verification checks'],
  },
  {
    id: 'evidence-verifier',
    name: 'Evidence Verifier',
    domain: 'verification',
    responsibility: 'Assigns PASS/WARNING/FAIL/INSUFFICIENT_DATA verification state.',
    allowedToolCategories: ['verification'],
    readWrite: 'read',
    verificationRequirements: ['Must include uncertainties and missing evidence'],
  },
  {
    id: 'torun-reference-resolver',
    name: 'Toruń Reference Resolver',
    domain: 'terra',
    responsibility: 'Resolves a named reference dataset without silently substituting incompatible records.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['URI, variable, unit, spatial scope and time range required before comparison'],
  },
  {
    id: 'global-analogue-scout',
    name: 'Global Analogue Scout',
    domain: 'terra',
    responsibility: 'Searches validated global hydrology cases for context-only analogues.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Analogy must never be reported as local causal proof'],
  },
  {
    id: 'hydrology-connectivity-analyst',
    name: 'Hydrology Connectivity Analyst',
    domain: 'terra',
    responsibility: 'Separates historical drainage-network documents from present-day flow evidence.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['Current flow claims require field or instrument evidence'],
  },
  {
    id: 'ground-verification-planner',
    name: 'Ground Verification Planner',
    domain: 'terra',
    responsibility: 'Defines safe in-situ checks needed before causal or hazard claims.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['No intervention without the responsible authority'],
  },
  {
    id: 'alert-public-safety-planner',
    name: 'Alert & Public Safety Planner',
    domain: 'terra',
    responsibility: 'Creates unsent preliminary alert drafts with named audiences, uncertainty and a human publication gate.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'write',
    verificationRequirements: ['No external delivery without human approval and recipient verification'],
  },
  {
    id: 'restoration-engineering-planner',
    name: 'Restoration Engineering Planner',
    domain: 'terra',
    responsibility: 'Proposes conditional monitoring, repair and regeneration options with permit and engineering prerequisites.',
    allowedToolCategories: ['terra', 'verification'],
    readWrite: 'read',
    verificationRequirements: ['No physical intervention from satellite imagery alone'],
  },
  {
    id: 'game-coordinator',
    name: 'Game Coordinator',
    domain: 'cube',
    responsibility: 'Coordinates cube AI experiment workflows.',
    allowedToolCategories: ['cube', 'verification'],
    readWrite: 'write',
    verificationRequirements: ['Human approval required for promotion'],
  },
  {
    id: 'qa-agent',
    name: 'QA Agent',
    domain: 'cube',
    responsibility: 'Runs tests and legality checks.',
    allowedToolCategories: ['cube', 'system'],
    readWrite: 'read',
    verificationRequirements: ['Regression status must be explicit'],
  },
  {
    id: 'visual-agent',
    name: 'Visual Agent',
    domain: 'visual',
    responsibility: 'Proposes reversible visual improvements.',
    allowedToolCategories: ['visual', 'verification'],
    readWrite: 'write',
    verificationRequirements: ['Before/after evidence required'],
  },
]
